package com.ft.backend.work.dao;

import com.ft.backend.work.model.AdsUserResourceInfo;

public interface AdsUserResourceInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ads_user_resource_info
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ads_user_resource_info
     *
     * @mbggenerated
     */
    int insert(AdsUserResourceInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ads_user_resource_info
     *
     * @mbggenerated
     */
    int insertSelective(AdsUserResourceInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ads_user_resource_info
     *
     * @mbggenerated
     */
    AdsUserResourceInfo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ads_user_resource_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(AdsUserResourceInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ads_user_resource_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(AdsUserResourceInfo record);
}