package com.ft.backend.work.dao;

import com.ft.backend.work.model.AdsUserAccount;

public interface AdsUserAccountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ads_user_account
     *
     * @mbggenerated
     */
    int insert(AdsUserAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ads_user_account
     *
     * @mbggenerated
     */
    int insertSelective(AdsUserAccount record);
}