package com.ft.backend.work.model;

public class AccountingRule {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accounting_rule.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accounting_rule.target_type
     *
     * @mbggenerated
     */
    private Byte targetType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accounting_rule.pin
     *
     * @mbggenerated
     */
    private String pin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accounting_rule.site
     *
     * @mbggenerated
     */
    private Byte site;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accounting_rule.app_code
     *
     * @mbggenerated
     */
    private String appCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accounting_rule.service_code
     *
     * @mbggenerated
     */
    private String serviceCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accounting_rule.out_account_type
     *
     * @mbggenerated
     */
    private Byte outAccountType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accounting_rule.out_account_day
     *
     * @mbggenerated
     */
    private Byte outAccountDay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accounting_rule.pay_time_value
     *
     * @mbggenerated
     */
    private Byte payTimeValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accounting_rule.pay_time_unit
     *
     * @mbggenerated
     */
    private Byte payTimeUnit;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accounting_rule.id
     *
     * @return the value of accounting_rule.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accounting_rule.id
     *
     * @param id the value for accounting_rule.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accounting_rule.target_type
     *
     * @return the value of accounting_rule.target_type
     *
     * @mbggenerated
     */
    public Byte getTargetType() {
        return targetType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accounting_rule.target_type
     *
     * @param targetType the value for accounting_rule.target_type
     *
     * @mbggenerated
     */
    public void setTargetType(Byte targetType) {
        this.targetType = targetType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accounting_rule.pin
     *
     * @return the value of accounting_rule.pin
     *
     * @mbggenerated
     */
    public String getPin() {
        return pin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accounting_rule.pin
     *
     * @param pin the value for accounting_rule.pin
     *
     * @mbggenerated
     */
    public void setPin(String pin) {
        this.pin = pin == null ? null : pin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accounting_rule.site
     *
     * @return the value of accounting_rule.site
     *
     * @mbggenerated
     */
    public Byte getSite() {
        return site;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accounting_rule.site
     *
     * @param site the value for accounting_rule.site
     *
     * @mbggenerated
     */
    public void setSite(Byte site) {
        this.site = site;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accounting_rule.app_code
     *
     * @return the value of accounting_rule.app_code
     *
     * @mbggenerated
     */
    public String getAppCode() {
        return appCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accounting_rule.app_code
     *
     * @param appCode the value for accounting_rule.app_code
     *
     * @mbggenerated
     */
    public void setAppCode(String appCode) {
        this.appCode = appCode == null ? null : appCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accounting_rule.service_code
     *
     * @return the value of accounting_rule.service_code
     *
     * @mbggenerated
     */
    public String getServiceCode() {
        return serviceCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accounting_rule.service_code
     *
     * @param serviceCode the value for accounting_rule.service_code
     *
     * @mbggenerated
     */
    public void setServiceCode(String serviceCode) {
        this.serviceCode = serviceCode == null ? null : serviceCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accounting_rule.out_account_type
     *
     * @return the value of accounting_rule.out_account_type
     *
     * @mbggenerated
     */
    public Byte getOutAccountType() {
        return outAccountType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accounting_rule.out_account_type
     *
     * @param outAccountType the value for accounting_rule.out_account_type
     *
     * @mbggenerated
     */
    public void setOutAccountType(Byte outAccountType) {
        this.outAccountType = outAccountType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accounting_rule.out_account_day
     *
     * @return the value of accounting_rule.out_account_day
     *
     * @mbggenerated
     */
    public Byte getOutAccountDay() {
        return outAccountDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accounting_rule.out_account_day
     *
     * @param outAccountDay the value for accounting_rule.out_account_day
     *
     * @mbggenerated
     */
    public void setOutAccountDay(Byte outAccountDay) {
        this.outAccountDay = outAccountDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accounting_rule.pay_time_value
     *
     * @return the value of accounting_rule.pay_time_value
     *
     * @mbggenerated
     */
    public Byte getPayTimeValue() {
        return payTimeValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accounting_rule.pay_time_value
     *
     * @param payTimeValue the value for accounting_rule.pay_time_value
     *
     * @mbggenerated
     */
    public void setPayTimeValue(Byte payTimeValue) {
        this.payTimeValue = payTimeValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accounting_rule.pay_time_unit
     *
     * @return the value of accounting_rule.pay_time_unit
     *
     * @mbggenerated
     */
    public Byte getPayTimeUnit() {
        return payTimeUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accounting_rule.pay_time_unit
     *
     * @param payTimeUnit the value for accounting_rule.pay_time_unit
     *
     * @mbggenerated
     */
    public void setPayTimeUnit(Byte payTimeUnit) {
        this.payTimeUnit = payTimeUnit;
    }
}