package com.ft.backend.work.model;

public class AccountingSubBill {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accounting_sub_bill.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accounting_sub_bill.bill_id
     *
     * @mbggenerated
     */
    private Byte billId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accounting_sub_bill.app_code
     *
     * @mbggenerated
     */
    private String appCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accounting_sub_bill.service_code
     *
     * @mbggenerated
     */
    private String serviceCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accounting_sub_bill.bill_fee
     *
     * @mbggenerated
     */
    private Double billFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accounting_sub_bill.bill_fee2
     *
     * @mbggenerated
     */
    private Double billFee2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accounting_sub_bill.discount_identitication
     *
     * @mbggenerated
     */
    private String discountIdentitication;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accounting_sub_bill.discount_value
     *
     * @mbggenerated
     */
    private Double discountValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accounting_sub_bill.discount_fee
     *
     * @mbggenerated
     */
    private Double discountFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accounting_sub_bill.coupon_identification
     *
     * @mbggenerated
     */
    private String couponIdentification;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accounting_sub_bill.coupon_fee
     *
     * @mbggenerated
     */
    private Double couponFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accounting_sub_bill.cash_coupon_identification
     *
     * @mbggenerated
     */
    private String cashCouponIdentification;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accounting_sub_bill.cash_coupon_fee
     *
     * @mbggenerated
     */
    private Double cashCouponFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accounting_sub_bill.balance_pay_fee
     *
     * @mbggenerated
     */
    private Double balancePayFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accounting_sub_bill.cash_pay_fee
     *
     * @mbggenerated
     */
    private Double cashPayFee;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accounting_sub_bill.id
     *
     * @return the value of accounting_sub_bill.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accounting_sub_bill.id
     *
     * @param id the value for accounting_sub_bill.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accounting_sub_bill.bill_id
     *
     * @return the value of accounting_sub_bill.bill_id
     *
     * @mbggenerated
     */
    public Byte getBillId() {
        return billId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accounting_sub_bill.bill_id
     *
     * @param billId the value for accounting_sub_bill.bill_id
     *
     * @mbggenerated
     */
    public void setBillId(Byte billId) {
        this.billId = billId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accounting_sub_bill.app_code
     *
     * @return the value of accounting_sub_bill.app_code
     *
     * @mbggenerated
     */
    public String getAppCode() {
        return appCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accounting_sub_bill.app_code
     *
     * @param appCode the value for accounting_sub_bill.app_code
     *
     * @mbggenerated
     */
    public void setAppCode(String appCode) {
        this.appCode = appCode == null ? null : appCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accounting_sub_bill.service_code
     *
     * @return the value of accounting_sub_bill.service_code
     *
     * @mbggenerated
     */
    public String getServiceCode() {
        return serviceCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accounting_sub_bill.service_code
     *
     * @param serviceCode the value for accounting_sub_bill.service_code
     *
     * @mbggenerated
     */
    public void setServiceCode(String serviceCode) {
        this.serviceCode = serviceCode == null ? null : serviceCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accounting_sub_bill.bill_fee
     *
     * @return the value of accounting_sub_bill.bill_fee
     *
     * @mbggenerated
     */
    public Double getBillFee() {
        return billFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accounting_sub_bill.bill_fee
     *
     * @param billFee the value for accounting_sub_bill.bill_fee
     *
     * @mbggenerated
     */
    public void setBillFee(Double billFee) {
        this.billFee = billFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accounting_sub_bill.bill_fee2
     *
     * @return the value of accounting_sub_bill.bill_fee2
     *
     * @mbggenerated
     */
    public Double getBillFee2() {
        return billFee2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accounting_sub_bill.bill_fee2
     *
     * @param billFee2 the value for accounting_sub_bill.bill_fee2
     *
     * @mbggenerated
     */
    public void setBillFee2(Double billFee2) {
        this.billFee2 = billFee2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accounting_sub_bill.discount_identitication
     *
     * @return the value of accounting_sub_bill.discount_identitication
     *
     * @mbggenerated
     */
    public String getDiscountIdentitication() {
        return discountIdentitication;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accounting_sub_bill.discount_identitication
     *
     * @param discountIdentitication the value for accounting_sub_bill.discount_identitication
     *
     * @mbggenerated
     */
    public void setDiscountIdentitication(String discountIdentitication) {
        this.discountIdentitication = discountIdentitication == null ? null : discountIdentitication.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accounting_sub_bill.discount_value
     *
     * @return the value of accounting_sub_bill.discount_value
     *
     * @mbggenerated
     */
    public Double getDiscountValue() {
        return discountValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accounting_sub_bill.discount_value
     *
     * @param discountValue the value for accounting_sub_bill.discount_value
     *
     * @mbggenerated
     */
    public void setDiscountValue(Double discountValue) {
        this.discountValue = discountValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accounting_sub_bill.discount_fee
     *
     * @return the value of accounting_sub_bill.discount_fee
     *
     * @mbggenerated
     */
    public Double getDiscountFee() {
        return discountFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accounting_sub_bill.discount_fee
     *
     * @param discountFee the value for accounting_sub_bill.discount_fee
     *
     * @mbggenerated
     */
    public void setDiscountFee(Double discountFee) {
        this.discountFee = discountFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accounting_sub_bill.coupon_identification
     *
     * @return the value of accounting_sub_bill.coupon_identification
     *
     * @mbggenerated
     */
    public String getCouponIdentification() {
        return couponIdentification;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accounting_sub_bill.coupon_identification
     *
     * @param couponIdentification the value for accounting_sub_bill.coupon_identification
     *
     * @mbggenerated
     */
    public void setCouponIdentification(String couponIdentification) {
        this.couponIdentification = couponIdentification == null ? null : couponIdentification.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accounting_sub_bill.coupon_fee
     *
     * @return the value of accounting_sub_bill.coupon_fee
     *
     * @mbggenerated
     */
    public Double getCouponFee() {
        return couponFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accounting_sub_bill.coupon_fee
     *
     * @param couponFee the value for accounting_sub_bill.coupon_fee
     *
     * @mbggenerated
     */
    public void setCouponFee(Double couponFee) {
        this.couponFee = couponFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accounting_sub_bill.cash_coupon_identification
     *
     * @return the value of accounting_sub_bill.cash_coupon_identification
     *
     * @mbggenerated
     */
    public String getCashCouponIdentification() {
        return cashCouponIdentification;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accounting_sub_bill.cash_coupon_identification
     *
     * @param cashCouponIdentification the value for accounting_sub_bill.cash_coupon_identification
     *
     * @mbggenerated
     */
    public void setCashCouponIdentification(String cashCouponIdentification) {
        this.cashCouponIdentification = cashCouponIdentification == null ? null : cashCouponIdentification.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accounting_sub_bill.cash_coupon_fee
     *
     * @return the value of accounting_sub_bill.cash_coupon_fee
     *
     * @mbggenerated
     */
    public Double getCashCouponFee() {
        return cashCouponFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accounting_sub_bill.cash_coupon_fee
     *
     * @param cashCouponFee the value for accounting_sub_bill.cash_coupon_fee
     *
     * @mbggenerated
     */
    public void setCashCouponFee(Double cashCouponFee) {
        this.cashCouponFee = cashCouponFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accounting_sub_bill.balance_pay_fee
     *
     * @return the value of accounting_sub_bill.balance_pay_fee
     *
     * @mbggenerated
     */
    public Double getBalancePayFee() {
        return balancePayFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accounting_sub_bill.balance_pay_fee
     *
     * @param balancePayFee the value for accounting_sub_bill.balance_pay_fee
     *
     * @mbggenerated
     */
    public void setBalancePayFee(Double balancePayFee) {
        this.balancePayFee = balancePayFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accounting_sub_bill.cash_pay_fee
     *
     * @return the value of accounting_sub_bill.cash_pay_fee
     *
     * @mbggenerated
     */
    public Double getCashPayFee() {
        return cashPayFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accounting_sub_bill.cash_pay_fee
     *
     * @param cashPayFee the value for accounting_sub_bill.cash_pay_fee
     *
     * @mbggenerated
     */
    public void setCashPayFee(Double cashPayFee) {
        this.cashPayFee = cashPayFee;
    }
}