package com.ft.backend.work.model;

public class AdsUserResourceInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ads_user_resource_info.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ads_user_resource_info.pin
     *
     * @mbggenerated
     */
    private String pin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ads_user_resource_info.type
     *
     * @mbggenerated
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ads_user_resource_info.state
     *
     * @mbggenerated
     */
    private String state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ads_user_resource_info.resource_id
     *
     * @mbggenerated
     */
    private String resourceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ads_user_resource_info.source_id
     *
     * @mbggenerated
     */
    private String sourceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ads_user_resource_info.order_number
     *
     * @mbggenerated
     */
    private String orderNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ads_user_resource_info.create_time
     *
     * @mbggenerated
     */
    private String createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ads_user_resource_info.update_time
     *
     * @mbggenerated
     */
    private String updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ads_user_resource_info.id
     *
     * @return the value of ads_user_resource_info.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ads_user_resource_info.id
     *
     * @param id the value for ads_user_resource_info.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ads_user_resource_info.pin
     *
     * @return the value of ads_user_resource_info.pin
     *
     * @mbggenerated
     */
    public String getPin() {
        return pin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ads_user_resource_info.pin
     *
     * @param pin the value for ads_user_resource_info.pin
     *
     * @mbggenerated
     */
    public void setPin(String pin) {
        this.pin = pin == null ? null : pin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ads_user_resource_info.type
     *
     * @return the value of ads_user_resource_info.type
     *
     * @mbggenerated
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ads_user_resource_info.type
     *
     * @param type the value for ads_user_resource_info.type
     *
     * @mbggenerated
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ads_user_resource_info.state
     *
     * @return the value of ads_user_resource_info.state
     *
     * @mbggenerated
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ads_user_resource_info.state
     *
     * @param state the value for ads_user_resource_info.state
     *
     * @mbggenerated
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ads_user_resource_info.resource_id
     *
     * @return the value of ads_user_resource_info.resource_id
     *
     * @mbggenerated
     */
    public String getResourceId() {
        return resourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ads_user_resource_info.resource_id
     *
     * @param resourceId the value for ads_user_resource_info.resource_id
     *
     * @mbggenerated
     */
    public void setResourceId(String resourceId) {
        this.resourceId = resourceId == null ? null : resourceId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ads_user_resource_info.source_id
     *
     * @return the value of ads_user_resource_info.source_id
     *
     * @mbggenerated
     */
    public String getSourceId() {
        return sourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ads_user_resource_info.source_id
     *
     * @param sourceId the value for ads_user_resource_info.source_id
     *
     * @mbggenerated
     */
    public void setSourceId(String sourceId) {
        this.sourceId = sourceId == null ? null : sourceId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ads_user_resource_info.order_number
     *
     * @return the value of ads_user_resource_info.order_number
     *
     * @mbggenerated
     */
    public String getOrderNumber() {
        return orderNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ads_user_resource_info.order_number
     *
     * @param orderNumber the value for ads_user_resource_info.order_number
     *
     * @mbggenerated
     */
    public void setOrderNumber(String orderNumber) {
        this.orderNumber = orderNumber == null ? null : orderNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ads_user_resource_info.create_time
     *
     * @return the value of ads_user_resource_info.create_time
     *
     * @mbggenerated
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ads_user_resource_info.create_time
     *
     * @param createTime the value for ads_user_resource_info.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime == null ? null : createTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ads_user_resource_info.update_time
     *
     * @return the value of ads_user_resource_info.update_time
     *
     * @mbggenerated
     */
    public String getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ads_user_resource_info.update_time
     *
     * @param updateTime the value for ads_user_resource_info.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime == null ? null : updateTime.trim();
    }
}