package com.ft.backend.work.model;

import java.math.BigDecimal;
import java.util.Date;

public class AdsUserAccount {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ads_user_account.pin
     *
     * @mbggenerated
     */
    private String pin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ads_user_account.billNumber
     *
     * @mbggenerated
     */
    private String billnumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ads_user_account.billAmount
     *
     * @mbggenerated
     */
    private BigDecimal billamount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ads_user_account.discountPay
     *
     * @mbggenerated
     */
    private BigDecimal discountpay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ads_user_account.couponPay
     *
     * @mbggenerated
     */
    private BigDecimal couponpay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ads_user_account.balancePay
     *
     * @mbggenerated
     */
    private BigDecimal balancepay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ads_user_account.deductStatus
     *
     * @mbggenerated
     */
    private Integer deductstatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ads_user_account.isSuccess
     *
     * @mbggenerated
     */
    private Boolean issuccess;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ads_user_account.message
     *
     * @mbggenerated
     */
    private String message;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ads_user_account.errorCode
     *
     * @mbggenerated
     */
    private Integer errorcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ads_user_account.billTime
     *
     * @mbggenerated
     */
    private Date billtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ads_user_account.orderNumber
     *
     * @mbggenerated
     */
    private String ordernumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ads_user_account.orderType
     *
     * @mbggenerated
     */
    private Byte ordertype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ads_user_account.dcsType
     *
     * @mbggenerated
     */
    private Byte dcstype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ads_user_account.startTime
     *
     * @mbggenerated
     */
    private Date starttime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ads_user_account.endTime
     *
     * @mbggenerated
     */
    private Date endtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ads_user_account.pin
     *
     * @return the value of ads_user_account.pin
     *
     * @mbggenerated
     */
    public String getPin() {
        return pin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ads_user_account.pin
     *
     * @param pin the value for ads_user_account.pin
     *
     * @mbggenerated
     */
    public void setPin(String pin) {
        this.pin = pin == null ? null : pin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ads_user_account.billNumber
     *
     * @return the value of ads_user_account.billNumber
     *
     * @mbggenerated
     */
    public String getBillnumber() {
        return billnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ads_user_account.billNumber
     *
     * @param billnumber the value for ads_user_account.billNumber
     *
     * @mbggenerated
     */
    public void setBillnumber(String billnumber) {
        this.billnumber = billnumber == null ? null : billnumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ads_user_account.billAmount
     *
     * @return the value of ads_user_account.billAmount
     *
     * @mbggenerated
     */
    public BigDecimal getBillamount() {
        return billamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ads_user_account.billAmount
     *
     * @param billamount the value for ads_user_account.billAmount
     *
     * @mbggenerated
     */
    public void setBillamount(BigDecimal billamount) {
        this.billamount = billamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ads_user_account.discountPay
     *
     * @return the value of ads_user_account.discountPay
     *
     * @mbggenerated
     */
    public BigDecimal getDiscountpay() {
        return discountpay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ads_user_account.discountPay
     *
     * @param discountpay the value for ads_user_account.discountPay
     *
     * @mbggenerated
     */
    public void setDiscountpay(BigDecimal discountpay) {
        this.discountpay = discountpay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ads_user_account.couponPay
     *
     * @return the value of ads_user_account.couponPay
     *
     * @mbggenerated
     */
    public BigDecimal getCouponpay() {
        return couponpay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ads_user_account.couponPay
     *
     * @param couponpay the value for ads_user_account.couponPay
     *
     * @mbggenerated
     */
    public void setCouponpay(BigDecimal couponpay) {
        this.couponpay = couponpay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ads_user_account.balancePay
     *
     * @return the value of ads_user_account.balancePay
     *
     * @mbggenerated
     */
    public BigDecimal getBalancepay() {
        return balancepay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ads_user_account.balancePay
     *
     * @param balancepay the value for ads_user_account.balancePay
     *
     * @mbggenerated
     */
    public void setBalancepay(BigDecimal balancepay) {
        this.balancepay = balancepay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ads_user_account.deductStatus
     *
     * @return the value of ads_user_account.deductStatus
     *
     * @mbggenerated
     */
    public Integer getDeductstatus() {
        return deductstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ads_user_account.deductStatus
     *
     * @param deductstatus the value for ads_user_account.deductStatus
     *
     * @mbggenerated
     */
    public void setDeductstatus(Integer deductstatus) {
        this.deductstatus = deductstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ads_user_account.isSuccess
     *
     * @return the value of ads_user_account.isSuccess
     *
     * @mbggenerated
     */
    public Boolean getIssuccess() {
        return issuccess;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ads_user_account.isSuccess
     *
     * @param issuccess the value for ads_user_account.isSuccess
     *
     * @mbggenerated
     */
    public void setIssuccess(Boolean issuccess) {
        this.issuccess = issuccess;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ads_user_account.message
     *
     * @return the value of ads_user_account.message
     *
     * @mbggenerated
     */
    public String getMessage() {
        return message;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ads_user_account.message
     *
     * @param message the value for ads_user_account.message
     *
     * @mbggenerated
     */
    public void setMessage(String message) {
        this.message = message == null ? null : message.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ads_user_account.errorCode
     *
     * @return the value of ads_user_account.errorCode
     *
     * @mbggenerated
     */
    public Integer getErrorcode() {
        return errorcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ads_user_account.errorCode
     *
     * @param errorcode the value for ads_user_account.errorCode
     *
     * @mbggenerated
     */
    public void setErrorcode(Integer errorcode) {
        this.errorcode = errorcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ads_user_account.billTime
     *
     * @return the value of ads_user_account.billTime
     *
     * @mbggenerated
     */
    public Date getBilltime() {
        return billtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ads_user_account.billTime
     *
     * @param billtime the value for ads_user_account.billTime
     *
     * @mbggenerated
     */
    public void setBilltime(Date billtime) {
        this.billtime = billtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ads_user_account.orderNumber
     *
     * @return the value of ads_user_account.orderNumber
     *
     * @mbggenerated
     */
    public String getOrdernumber() {
        return ordernumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ads_user_account.orderNumber
     *
     * @param ordernumber the value for ads_user_account.orderNumber
     *
     * @mbggenerated
     */
    public void setOrdernumber(String ordernumber) {
        this.ordernumber = ordernumber == null ? null : ordernumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ads_user_account.orderType
     *
     * @return the value of ads_user_account.orderType
     *
     * @mbggenerated
     */
    public Byte getOrdertype() {
        return ordertype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ads_user_account.orderType
     *
     * @param ordertype the value for ads_user_account.orderType
     *
     * @mbggenerated
     */
    public void setOrdertype(Byte ordertype) {
        this.ordertype = ordertype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ads_user_account.dcsType
     *
     * @return the value of ads_user_account.dcsType
     *
     * @mbggenerated
     */
    public Byte getDcstype() {
        return dcstype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ads_user_account.dcsType
     *
     * @param dcstype the value for ads_user_account.dcsType
     *
     * @mbggenerated
     */
    public void setDcstype(Byte dcstype) {
        this.dcstype = dcstype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ads_user_account.startTime
     *
     * @return the value of ads_user_account.startTime
     *
     * @mbggenerated
     */
    public Date getStarttime() {
        return starttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ads_user_account.startTime
     *
     * @param starttime the value for ads_user_account.startTime
     *
     * @mbggenerated
     */
    public void setStarttime(Date starttime) {
        this.starttime = starttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ads_user_account.endTime
     *
     * @return the value of ads_user_account.endTime
     *
     * @mbggenerated
     */
    public Date getEndtime() {
        return endtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ads_user_account.endTime
     *
     * @param endtime the value for ads_user_account.endTime
     *
     * @mbggenerated
     */
    public void setEndtime(Date endtime) {
        this.endtime = endtime;
    }
}