package com.ft.backend.work.model;

import java.util.Date;

public class ConsumeRecord {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column consume_record.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column consume_record.pin
     *
     * @mbggenerated
     */
    private String pin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column consume_record.resource_id
     *
     * @mbggenerated
     */
    private String resourceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column consume_record.formula
     *
     * @mbggenerated
     */
    private String formula;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column consume_record.billing_type
     *
     * @mbggenerated
     */
    private Byte billingType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column consume_record.price_snapshot
     *
     * @mbggenerated
     */
    private String priceSnapshot;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column consume_record.start_time
     *
     * @mbggenerated
     */
    private Date startTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column consume_record.end_time
     *
     * @mbggenerated
     */
    private Date endTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column consume_record.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column consume_record.bill_fee
     *
     * @mbggenerated
     */
    private Double billFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column consume_record.bill_fee2
     *
     * @mbggenerated
     */
    private Double billFee2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column consume_record.is_bill_generated
     *
     * @mbggenerated
     */
    private Byte isBillGenerated;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consume_record.id
     *
     * @return the value of consume_record.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column consume_record.id
     *
     * @param id the value for consume_record.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consume_record.pin
     *
     * @return the value of consume_record.pin
     *
     * @mbggenerated
     */
    public String getPin() {
        return pin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column consume_record.pin
     *
     * @param pin the value for consume_record.pin
     *
     * @mbggenerated
     */
    public void setPin(String pin) {
        this.pin = pin == null ? null : pin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consume_record.resource_id
     *
     * @return the value of consume_record.resource_id
     *
     * @mbggenerated
     */
    public String getResourceId() {
        return resourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column consume_record.resource_id
     *
     * @param resourceId the value for consume_record.resource_id
     *
     * @mbggenerated
     */
    public void setResourceId(String resourceId) {
        this.resourceId = resourceId == null ? null : resourceId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consume_record.formula
     *
     * @return the value of consume_record.formula
     *
     * @mbggenerated
     */
    public String getFormula() {
        return formula;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column consume_record.formula
     *
     * @param formula the value for consume_record.formula
     *
     * @mbggenerated
     */
    public void setFormula(String formula) {
        this.formula = formula == null ? null : formula.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consume_record.billing_type
     *
     * @return the value of consume_record.billing_type
     *
     * @mbggenerated
     */
    public Byte getBillingType() {
        return billingType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column consume_record.billing_type
     *
     * @param billingType the value for consume_record.billing_type
     *
     * @mbggenerated
     */
    public void setBillingType(Byte billingType) {
        this.billingType = billingType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consume_record.price_snapshot
     *
     * @return the value of consume_record.price_snapshot
     *
     * @mbggenerated
     */
    public String getPriceSnapshot() {
        return priceSnapshot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column consume_record.price_snapshot
     *
     * @param priceSnapshot the value for consume_record.price_snapshot
     *
     * @mbggenerated
     */
    public void setPriceSnapshot(String priceSnapshot) {
        this.priceSnapshot = priceSnapshot == null ? null : priceSnapshot.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consume_record.start_time
     *
     * @return the value of consume_record.start_time
     *
     * @mbggenerated
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column consume_record.start_time
     *
     * @param startTime the value for consume_record.start_time
     *
     * @mbggenerated
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consume_record.end_time
     *
     * @return the value of consume_record.end_time
     *
     * @mbggenerated
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column consume_record.end_time
     *
     * @param endTime the value for consume_record.end_time
     *
     * @mbggenerated
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consume_record.create_time
     *
     * @return the value of consume_record.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column consume_record.create_time
     *
     * @param createTime the value for consume_record.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consume_record.bill_fee
     *
     * @return the value of consume_record.bill_fee
     *
     * @mbggenerated
     */
    public Double getBillFee() {
        return billFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column consume_record.bill_fee
     *
     * @param billFee the value for consume_record.bill_fee
     *
     * @mbggenerated
     */
    public void setBillFee(Double billFee) {
        this.billFee = billFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consume_record.bill_fee2
     *
     * @return the value of consume_record.bill_fee2
     *
     * @mbggenerated
     */
    public Double getBillFee2() {
        return billFee2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column consume_record.bill_fee2
     *
     * @param billFee2 the value for consume_record.bill_fee2
     *
     * @mbggenerated
     */
    public void setBillFee2(Double billFee2) {
        this.billFee2 = billFee2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consume_record.is_bill_generated
     *
     * @return the value of consume_record.is_bill_generated
     *
     * @mbggenerated
     */
    public Byte getIsBillGenerated() {
        return isBillGenerated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column consume_record.is_bill_generated
     *
     * @param isBillGenerated the value for consume_record.is_bill_generated
     *
     * @mbggenerated
     */
    public void setIsBillGenerated(Byte isBillGenerated) {
        this.isBillGenerated = isBillGenerated;
    }
}